//! Turning a colour into channel values, by a strategy the caller picks.
//!
//! The reader-facing account of all this is on [`ColourStrategy`], because
//! this module is private and its items are re-exported from
//! [`protocol`](super) — rustdoc renders no page for it, so anything written
//! here is for whoever is editing the file.
//!
//! [`ColourStrategy::Trapezoid`] is a port of `pywizlight`'s `rgbcw.py`,
//! deliberately faithful down to its rounding and its surprises. It is checked
//! against a table of values recorded from the original
//! (`tests/data/rgbcw_golden.json`, regenerated by the script beside it), so
//! **an "improvement" made here will fail the tests** — which is the intent.
//! A port that disagrees with what it was ported from is worth less than one
//! that does not, and any deliberate deviation belongs after the hardware A/B,
//! with the golden table regenerated and the reason recorded.

use std::f64::consts::{PI, TAU};

use crate::error::{Error, Result};

/// A point in the hue plane, where the algorithm does its work.
type Vec2 = (f64, f64);

/// Close enough to zero for three orders of magnitude of colour resolution.
/// `pywizlight`'s value, and it is compared against a *squared* length in
/// [`length`], which is its choice too.
const EPSILON: f64 = 1.0e-5;

/// The largest white value the blend will emit, out of a possible 255.
///
/// `pywizlight`'s `CWMAX`, unexplained there and unverified here. Halving the
/// available white presumably leaves the colour emitters something to work
/// with out of the shared power budget.
pub const CW_MAX: u8 = 128;

/// The primaries, 120° apart, as unit vectors in the hue plane.
///
/// Spelled out rather than computed, and that is worth more than the `const`
/// it buys. These are the `f64`s CPython's `cos`/`sin` produced for 0, 2π/3
/// and 4π/3 on the machine the golden table was recorded on, last-bit error
/// and all — so the port starts from the numbers the original started from.
///
/// Computing them here instead would hand the starting point to whichever
/// `libm` the build lands on, and **they do not agree**: the last bit of
/// `cos(2π/3)` differs between platforms, which CI caught. `pywizlight`
/// inherits that variation. Freezing the constants means this crate does not,
/// and it is why the `rgb2rgbcw` golden test can demand an exact byte on every
/// platform rather than settling for a tolerance.
const BASIS: [Vec2; 3] = [
    (1.0, 0.0),
    (-0.499_999_999_999_999_83, 0.866_025_403_784_438_7),
    (-0.500_000_000_000_000_4, -0.866_025_403_784_438_4),
];

/// `cos(2π/3 − EPSILON)`: the dot product a hue vector must exceed to count a
/// primary as one of its components. Being a hair above `cos(2π/3)` is what
/// makes a hue sitting exactly on a primary select that primary alone instead
/// of it and both its neighbours.
const MAX_ANGLE: f64 = -0.499_991_339_720_962_05;

fn dot(a: Vec2, b: Vec2) -> f64 {
    a.0 * b.0 + a.1 * b.1
}

fn scale(v: Vec2, by: f64) -> Vec2 {
    (v.0 * by, v.1 * by)
}

/// The vector's magnitude, or zero when it is negligible.
///
/// The threshold is on the *squared* length, so anything shorter than
/// `sqrt(1e-5)` ≈ 0.0032 reports as zero. That is `pywizlight`'s behaviour and
/// it is load-bearing: it is what makes a very dark RGB triple convert to a
/// pure white rather than to a wildly amplified hue.
fn length(v: Vec2) -> f64 {
    let squared = dot(v, v);
    if squared > EPSILON {
        squared.sqrt()
    } else {
        0.0
    }
}

/// Where an RGB triple in `0.0..=1.0` sits in the hue plane.
fn hue_vector(rgb: [f64; 3]) -> Vec2 {
    let (x, y) = (0..3).fold((0.0, 0.0), |acc, i| {
        let component = scale(BASIS[i], rgb[i]);
        (acc.0 + component.0, acc.1 + component.1)
    });
    (x, y)
}

/// The fully saturated colour at this hue, as three coefficients in
/// `0.0..=1.0`.
///
/// `hue_vec` must be a unit vector. The hue is expressed as a combination of
/// **at most two** primaries: exactly one when it sits on a primary, two
/// otherwise. The area outside the hexagon spanned by the primaries is not
/// reachable, which shows up as coefficients above 1 for every hue that is
/// neither a primary nor a bisector, so both are divided by the larger — the
/// gamut rescale, which preserves the hue and gives up some brightness.
fn saturated_rgb(hue_vec: Vec2) -> [f64; 3] {
    let mut selected = [0usize; 3];
    let mut count = 0;
    for (index, basis) in BASIS.iter().enumerate() {
        if dot(hue_vec, *basis) > MAX_ANGLE {
            selected[count] = index;
            count += 1;
        }
    }

    let mut rgb = [0.0; 3];
    let [first, second, _] = selected;
    if count != 2 {
        // The three cones are 240° wide and 120° apart, so a unit vector falls
        // in exactly two of them, or in one when it lies on a primary. Neither
        // zero nor three is reachable; if it somehow were, every selected
        // primary at full is the answer that keeps the hue.
        for index in &selected[..count] {
            rgb[*index] = 1.0;
        }
        return rgb;
    }

    let (basis0, basis1) = (BASIS[first], BASIS[second]);
    // The line through the origin along `basis1`, as Ax + By = 0.
    let line = (basis1.1, -basis1.0);
    // Where the ray from the hue vector back along `basis0` crosses it. The
    // two are never parallel, so there is always exactly one crossing.
    let coeff0 = dot(hue_vec, line) / dot(basis0, line);
    let intersection = {
        let back = scale(basis0, -coeff0);
        (back.0 + hue_vec.0, back.1 + hue_vec.1)
    };
    let coeff1 = dot(intersection, basis1);

    let max_coeff = coeff0.max(coeff1);
    rgb[first] = (coeff0 / max_coeff).min(1.0);
    rgb[second] = (coeff1 / max_coeff).min(1.0);
    rgb
}

/// The trapezoid: hue and saturation to three colour channels plus a white.
///
/// Saturation is discontinuous at 0.5, and both halves are described on
/// [`ColourStrategy::Trapezoid`], which is where a caller will look.
fn trapezoid(hue_vec: Vec2, saturation: f64) -> ([u8; 3], u8) {
    let mut rgb = if saturation <= EPSILON {
        [0.0; 3]
    } else {
        saturated_rgb(hue_vec)
    };

    let white = if saturation >= 0.5 {
        1.0 - ((saturation - 0.5) * 2.0)
    } else {
        let by = saturation * 2.0;
        rgb = [rgb[0] * by, rgb[1] * by, rgb[2] * by];
        1.0
    };

    // Truncation, not rounding: `pywizlight` truncates, so the port does too.
    // A cast saturates in Rust, which is also what is wanted at both ends —
    // the gamut rescale can leave a coefficient a hair below zero.
    let channels = [
        (rgb[0] * 255.0) as u8,
        (rgb[1] * 255.0) as u8,
        (rgb[2] * 255.0) as u8,
    ];
    (channels, (white * f64::from(CW_MAX)).max(0.0) as u8)
}

/// Which of the two white emitters a blend drives.
///
/// See [`ColourStrategy`](ColourStrategy#cold-or-warm): `pywizlight` computes
/// a cold white and then sends it as a warm one, so both are offered here and
/// neither is claimed to be the right one.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum WhiteChannel {
    /// The ~6200 K emitter, `c`. What the algorithm says it computes.
    Cold,
    /// The ~2800 K emitter, `w`. What `pywizlight` actually sends.
    Warm,
}

/// How a colour becomes channel values.
///
/// An RGB bulb has **five emitters** — red, green, blue, a cold white and a
/// warm white — and one `setPilot` drives all of them. So there is no single
/// right answer to "which channels make this colour": the same hue can be
/// mixed from the three colour emitters alone, or from fewer of them plus
/// white. This is that choice, and it belongs to the caller.
///
/// The two strategies differ only over *unsaturated* colour. At full
/// saturation both send the same three channels and no white; the further a
/// colour is from saturated, the further apart they get.
///
/// ```
/// use wizlight::protocol::{ColourStrategy, PilotBuilder, WhiteChannel};
///
/// // A pale peach. Raw RGB mixes it from the colour emitters alone…
/// let raw = ColourStrategy::Rgb.apply_rgb((255, 200, 170));
/// assert_eq!((raw.r, raw.g, raw.b, raw.c, raw.w), (255, 200, 170, 0, 0));
///
/// // …the trapezoid mixes it from a full white, tinted with orange.
/// let blended = ColourStrategy::Trapezoid(WhiteChannel::Cold).apply_rgb((255, 200, 170));
/// assert_eq!((blended.r, blended.g, blended.b, blended.c, blended.w), (149, 52, 0, 128, 0));
///
/// let request = PilotBuilder::new().colour(blended).set_pilot()?;
/// # Ok::<(), wizlight::Error>(())
/// ```
///
/// # The shared power budget
///
/// The five emitters draw on **one power budget**, which is why every channel
/// at `255` is not the brightest setting the bulb has: asking for everything
/// splits the same power five ways. Mixing a pastel from white plus a little
/// colour therefore tends to look better *and* brighter than mixing it from
/// three colour emitters at partial strength, and that is the whole reason
/// [`ColourStrategy::Trapezoid`] exists.
///
/// This paragraph is **inherited, not measured**: the emitter count, the
/// ~6200 K and ~2800 K figures and the shared budget all come from
/// `pywizlight`'s notes. None of it has been checked against hardware here,
/// and neither has the claim that the blend looks better — which is why both
/// strategies exist rather than just the better one.
///
/// # Cold or warm?
///
/// `pywizlight` contradicts itself, and the contradiction is why
/// [`WhiteChannel`] is a parameter at all: its algorithm computes a value it
/// calls `cw` and documents as the cold white, and its client then sends that
/// number on **`w`, the warm white channel**. One of the two is a bug, and the
/// source cannot say which. So both are offered, neither is presented as
/// correct, and they will not look the same on a wall.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ColourStrategy {
    /// Send the colour as it is, and leave both whites at zero.
    ///
    /// The channels are the bulb's to mix, so a pastel is three colour
    /// emitters at partial strength. Punchier on saturated colour, where there
    /// is nothing for white to add; whites and pastels come out dimmer and
    /// less convincing than the white emitters would make them.
    Rgb,
    /// Blend white in as saturation falls — `pywizlight`'s algorithm, and the
    /// reason it is called the trapezoid is the shape the two chosen primaries
    /// and the gamut rescale cut out of the hue plane.
    ///
    /// Better pastels and far better near-whites, at the cost of never using
    /// more than half the white channel's range and of a **discontinuity at
    /// saturation 0.5**, which is the trick of it:
    ///
    /// - **above 0.5** the colour stays fully saturated and the white ramps
    ///   from [`CW_MAX`] down to zero, so desaturating adds white light
    ///   instead of washing the colour out;
    /// - **below 0.5** the white is pinned at [`CW_MAX`] and the colour fades
    ///   to black, so the colour emitters do no more than tint a white.
    ///
    /// The consequence to know is that **zero saturation is a lit white, not
    /// darkness**: no saturation means no colour, not no light. Brightness is
    /// [`dimming`](super::PilotBuilder::dimming)'s job and off is
    /// [`state`](super::PilotBuilder::state)'s.
    Trapezoid(WhiteChannel),
}

impl ColourStrategy {
    /// Converts an RGB triple.
    ///
    /// **[`ColourStrategy::Trapezoid`] reads a dim colour as a desaturated
    /// one.** It recovers saturation from the *length* of the triple, having
    /// no other way to know it, so `(128, 0, 0)` is a red at saturation 0.5
    /// and converts to a full red plus a full white — brighter than what went
    /// in, and pink. Halving a triple to dim it is therefore a mistake here:
    /// pass the colour at full strength and dim with
    /// [`dimming`](super::PilotBuilder::dimming), or use
    /// [`apply_hs`](ColourStrategy::apply_hs) and say what the saturation
    /// really is.
    ///
    /// ```
    /// use wizlight::protocol::{ColourStrategy, WhiteChannel};
    ///
    /// let blend = ColourStrategy::Trapezoid(WhiteChannel::Cold);
    /// assert_eq!(blend.apply_rgb((255, 0, 0)).c, 0);    // saturated red
    /// assert_eq!(blend.apply_rgb((128, 0, 0)).c, 127);  // half as long: pink
    /// ```
    ///
    /// [`ColourStrategy::Rgb`] passes the triple through untouched, and so has
    /// no opinion about any of this.
    #[must_use]
    pub fn apply_rgb(self, rgb: (u8, u8, u8)) -> Rgbcw {
        let (r, g, b) = rgb;
        match self {
            Self::Rgb => Rgbcw {
                r,
                g,
                b,
                c: 0,
                w: 0,
            },
            Self::Trapezoid(white) => {
                // Scale by the reciprocal, once, as the original does.
                let scaled = [
                    f64::from(r) * (1.0 / 255.0),
                    f64::from(g) * (1.0 / 255.0),
                    f64::from(b) * (1.0 / 255.0),
                ];
                let vector = hue_vector(scaled);
                let saturation = length(vector);
                let unit = if saturation > EPSILON {
                    scale(vector, 1.0 / saturation)
                } else {
                    vector
                };
                Rgbcw::blend(trapezoid(unit, saturation), white)
            }
        }
    }

    /// Converts a hue and saturation.
    ///
    /// This is the input the trapezoid is written for, and the one to prefer:
    /// going through RGB throws away the saturation the caller knew and then
    /// recovers it from the geometry.
    #[must_use]
    pub fn apply_hs(self, hs: Hs) -> Rgbcw {
        let radians = (hs.hue / 360.0) * TAU;
        let unit = (radians.cos(), radians.sin());
        let saturation = hs.saturation / 100.0;
        match self {
            // Standard HSV at full value: the saturated hue, mixed towards
            // white in colour space rather than by lighting a white emitter.
            Self::Rgb => {
                let rgb = saturated_rgb(unit);
                let towards_white =
                    |component: f64| ((component * saturation + (1.0 - saturation)) * 255.0) as u8;
                Rgbcw {
                    r: towards_white(rgb[0]),
                    g: towards_white(rgb[1]),
                    b: towards_white(rgb[2]),
                    c: 0,
                    w: 0,
                }
            }
            Self::Trapezoid(white) => Rgbcw::blend(trapezoid(unit, saturation), white),
        }
    }
}

/// A hue and saturation, as an angle in degrees and a percentage.
///
/// Brightness is deliberately not part of it: on a WiZ bulb that is `dimming`,
/// a separate parameter that survives a colour change.
#[derive(Clone, Copy, Debug, PartialEq, PartialOrd)]
pub struct Hs {
    hue: f64,
    saturation: f64,
}

impl Hs {
    /// Builds a hue/saturation pair.
    ///
    /// The hue wraps, so `-30.0`, `330.0` and `690.0` are one colour and none
    /// of them is an error. Saturation does not: a percentage outside
    /// `0.0..=100.0` is a caller's arithmetic gone wrong, not a colour.
    ///
    /// ```
    /// use wizlight::protocol::Hs;
    ///
    /// assert_eq!(Hs::new(-30.0, 50.0)?.hue(), 330.0);
    /// assert!(Hs::new(0.0, 101.0).is_err());
    /// assert!(Hs::new(f64::NAN, 50.0).is_err());
    /// # Ok::<(), wizlight::Error>(())
    /// ```
    ///
    /// # Errors
    ///
    /// Returns [`Error::InvalidParam`] if either value is not finite, or if
    /// `saturation` is outside `0.0..=100.0`.
    pub fn new(hue: f64, saturation: f64) -> Result<Self> {
        if !hue.is_finite() || !saturation.is_finite() {
            return Err(Error::InvalidParam {
                message: format!("hue and saturation must be finite, got {hue} and {saturation}"),
            });
        }
        if !(0.0..=100.0).contains(&saturation) {
            return Err(Error::InvalidParam {
                message: format!("saturation must be 0..=100, got {saturation}"),
            });
        }
        Ok(Self {
            hue: hue.rem_euclid(360.0),
            saturation,
        })
    }

    /// The hue in degrees, in `0.0..360.0`.
    #[must_use]
    pub const fn hue(self) -> f64 {
        self.hue
    }

    /// The saturation as a percentage, in `0.0..=100.0`.
    #[must_use]
    pub const fn saturation(self) -> f64 {
        self.saturation
    }
}

/// Channel values ready to send: the three colours and the two whites.
///
/// Produced by [`ColourStrategy`], consumed by
/// [`PilotBuilder::colour`](super::PilotBuilder::colour). Every field is
/// always set, including the zeroes — a colour is fully specified by all five
/// channels, and sending only some of them leaves the rest wherever the last
/// request left them.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Rgbcw {
    /// Red.
    pub r: u8,
    /// Green.
    pub g: u8,
    /// Blue.
    pub b: u8,
    /// Cold white, ~6200 K.
    pub c: u8,
    /// Warm white, ~2800 K.
    pub w: u8,
}

impl Rgbcw {
    /// Places a blend's single white value on the chosen channel.
    fn blend((rgb, white): ([u8; 3], u8), channel: WhiteChannel) -> Self {
        let [r, g, b] = rgb;
        let (c, w) = match channel {
            WhiteChannel::Cold => (white, 0),
            WhiteChannel::Warm => (0, white),
        };
        Self { r, g, b, c, w }
    }

    /// Reads these channels back as a hue and saturation — `pywizlight`'s
    /// `rgbcw2hs`.
    ///
    /// This inverts [`ColourStrategy::Trapezoid`], and only approximately.
    /// Saturation comes from the white channel above 0.5 and from the length
    /// of the hue vector at 0.5 and below, and the second of those **ignores
    /// the gamut rescale the forward conversion applied**. Measured over every
    /// hue at 0.25° and every saturation at 0.5%:
    ///
    /// | | worst error |
    /// | --- | --- |
    /// | saturation, above 0.5 | 0.375 points — the white channel's own quantisation |
    /// | saturation, at 0.5 and below | 6.7 points, and up to a third of the value in relative terms |
    /// | hue, saturation ≥ 25 | 0.5° |
    /// | hue, saturation ≥ 5 | 2.3° |
    /// | hue, saturation ≥ 1 | 12.3° |
    ///
    /// So this is a good reading of a vivid colour and a poor one of a near
    /// white — where there is barely any colour left to read. Above the step
    /// it round-trips to the same channels; below it, feeding a readback back
    /// through the conversion pales the colour a little each time.
    ///
    /// Whichever white is larger is the one used: the blend only ever drives
    /// one of them, but a bulb that some other client has been talking to can
    /// report both.
    #[must_use]
    pub fn to_hs(self) -> Hs {
        let rgb = [
            f64::from(self.r) * (1.0 / 255.0),
            f64::from(self.g) * (1.0 / 255.0),
            f64::from(self.b) * (1.0 / 255.0),
        ];
        let vector = hue_vector(rgb);
        let white = f64::from(self.c.max(self.w).min(CW_MAX)) / f64::from(CW_MAX);

        let saturation = if white == 1.0 {
            // The white is pinned, so the colour carries the saturation, and
            // it ran from nothing to unit length over the lower half.
            length(vector) * 0.5
        } else {
            // The colour is fully saturated and the white is what was mixed
            // into it.
            1.0 - (white / 2.0)
        };

        let mut hue = vector.1.atan2(vector.0);
        if hue < 0.0 {
            // `atan2` answers in `-π..=π`, so one turn is always enough.
            hue += TAU;
        }
        Hs {
            // A hue of exactly 360° can survive the multiply; it is 0°.
            hue: (hue * (180.0 / PI)).rem_euclid(360.0),
            saturation: saturation * 100.0,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The basis is written out as literals, so it is checked against what
    /// computes them — but only to within a bit, because **the platforms
    /// disagree in that bit**. `cos(2π/3)` is not the same `f64` on macOS as
    /// on Linux, and CI failed on exactly that before this test was loosened.
    ///
    /// Demanding equality here would mean demanding it of every `libm` the
    /// crate is ever built against, which is not a promise any of them makes.
    /// The constants stay frozen precisely so that the *conversion* is
    /// identical everywhere even though `cos` is not; this checks they are
    /// still the right constants, not that the local `cos` agrees to the bit.
    #[test]
    fn the_basis_is_the_one_the_original_computes() {
        // One ULP either side, at this magnitude.
        let close = |a: f64, b: f64| (a - b).abs() <= f64::EPSILON;
        let angle = TAU / 3.0;
        for (index, radians) in [0.0, angle, angle * 2.0].into_iter().enumerate() {
            let (cos, sin) = (radians.cos(), radians.sin());
            assert!(
                close(BASIS[index].0, cos) && close(BASIS[index].1, sin),
                "basis {index} is {:?}, this platform computes {:?}",
                BASIS[index],
                (cos, sin),
            );
        }
        let computed = (TAU / 3.0 - EPSILON).cos();
        assert!(close(MAX_ANGLE, computed), "{MAX_ANGLE} vs {computed}");
    }

    /// [`length`]'s threshold is faithful to the original and **cannot fire
    /// for any input this crate accepts**, which is worth writing down before
    /// someone deletes it as dead code or trusts it as live.
    ///
    /// Both callers start from bytes. A hue vector is
    /// `(r·b₀ + g·b₁ + b·b₂) / 255`, and since `b₀ + b₁ + b₂ = 0` that is the
    /// hexagonal lattice spanned by `b₀` and `b₁`, whose shortest non-zero
    /// vector is one whole unit — 1/255, or 0.0039. The threshold zeroes
    /// anything below `sqrt(1e-5)`, or 0.0032. Nothing lands in between, and a
    /// grey lands at zero, where the threshold changes nothing.
    #[test]
    fn the_length_threshold_is_faithful_and_unreachable() {
        // What it does, so that removing it is a visible change.
        assert_eq!(length((0.002, 0.0)), 0.0);
        assert_eq!(length((0.004, 0.0)), 0.004);

        // And why nothing ever asks it to. 255 of each primary covers every
        // triple, the two coefficients being channel differences.
        let mut shortest = f64::INFINITY;
        for i in -255..=255 {
            for j in -255..=255 {
                if (i, j) == (0, 0) {
                    continue;
                }
                let (x, y) = (f64::from(i), f64::from(j));
                let vector = (
                    x * BASIS[0].0 + y * BASIS[1].0,
                    x * BASIS[0].1 + y * BASIS[1].1,
                );
                shortest = shortest.min(dot(vector, vector).sqrt());
            }
        }
        assert!(
            (shortest - 1.0).abs() < 1e-9,
            "shortest lattice step {shortest}"
        );
        assert!(
            shortest / 255.0 > EPSILON.sqrt(),
            "the threshold is reachable"
        );
    }

    /// The discontinuity is the algorithm's defining feature, so it gets its
    /// own test rather than being left to the golden table.
    #[test]
    fn saturation_is_discontinuous_at_half() {
        let blend = |saturation| {
            ColourStrategy::Trapezoid(WhiteChannel::Cold)
                .apply_hs(Hs::new(0.0, saturation).expect("in range"))
        };

        // Below the step: white pinned, colour fading to black.
        assert_eq!(
            blend(0.0),
            Rgbcw {
                r: 0,
                g: 0,
                b: 0,
                c: 128,
                w: 0
            }
        );
        assert_eq!(
            blend(25.0),
            Rgbcw {
                r: 127,
                g: 0,
                b: 0,
                c: 128,
                w: 0
            }
        );
        assert_eq!(
            blend(49.9),
            Rgbcw {
                r: 254,
                g: 0,
                b: 0,
                c: 128,
                w: 0
            }
        );
        // At and above it: colour saturated, white ramping away.
        assert_eq!(
            blend(50.0),
            Rgbcw {
                r: 255,
                g: 0,
                b: 0,
                c: 128,
                w: 0
            }
        );
        assert_eq!(
            blend(75.0),
            Rgbcw {
                r: 255,
                g: 0,
                b: 0,
                c: 64,
                w: 0
            }
        );
        assert_eq!(
            blend(100.0),
            Rgbcw {
                r: 255,
                g: 0,
                b: 0,
                c: 0,
                w: 0
            }
        );
    }

    /// The trap in the algorithm: no saturation means white light, not none.
    #[test]
    fn zero_saturation_is_a_lit_white_not_darkness() {
        let blend = ColourStrategy::Trapezoid(WhiteChannel::Cold);
        assert_eq!(blend.apply_rgb((0, 0, 0)).c, 128);
        assert_eq!(blend.apply_rgb((0, 0, 0)).r, 0);
        // Raw RGB has no such surprise: black in, black out.
        assert_eq!(ColourStrategy::Rgb.apply_rgb((0, 0, 0)), Rgbcw::default());
    }

    /// The blend has no brightness input, so it reads a short RGB vector as a
    /// desaturated colour. Halving a triple makes it *paler*, not dimmer —
    /// and, because the white emitter joins in, not even darker.
    #[test]
    fn the_blend_reads_a_dim_colour_as_a_pale_one() {
        let blend = ColourStrategy::Trapezoid(WhiteChannel::Warm);
        assert_eq!(
            blend.apply_rgb((255, 0, 0)),
            Rgbcw {
                r: 255,
                g: 0,
                b: 0,
                c: 0,
                w: 0
            }
        );
        assert_eq!(
            blend.apply_rgb((128, 0, 0)),
            Rgbcw {
                r: 255,
                g: 0,
                b: 0,
                c: 0,
                w: 127
            }
        );
        // Below half length the white pins and the colour is what fades.
        assert_eq!(
            blend.apply_rgb((64, 0, 0)),
            Rgbcw {
                r: 128,
                g: 0,
                b: 0,
                c: 0,
                w: 128
            }
        );
    }

    /// Both whites are reachable, and nothing else moves when the choice does.
    #[test]
    fn the_white_channel_is_the_callers_choice() {
        let hs = Hs::new(210.0, 20.0).expect("in range");
        let cold = ColourStrategy::Trapezoid(WhiteChannel::Cold).apply_hs(hs);
        let warm = ColourStrategy::Trapezoid(WhiteChannel::Warm).apply_hs(hs);
        assert_eq!((cold.r, cold.g, cold.b), (warm.r, warm.g, warm.b));
        assert_eq!((cold.c, cold.w), (128, 0));
        assert_eq!((warm.c, warm.w), (0, 128));
    }

    /// Raw RGB from hue/saturation is plain HSV at full value: the same hue,
    /// mixed towards white in colour space instead of with a white emitter.
    #[test]
    fn raw_rgb_desaturates_towards_white() {
        let raw = |saturation| {
            ColourStrategy::Rgb.apply_hs(Hs::new(120.0, saturation).expect("in range"))
        };
        assert_eq!(
            raw(100.0),
            Rgbcw {
                r: 0,
                g: 255,
                b: 0,
                c: 0,
                w: 0
            }
        );
        assert_eq!(
            raw(50.0),
            Rgbcw {
                r: 127,
                g: 255,
                b: 127,
                c: 0,
                w: 0
            }
        );
        assert_eq!(
            raw(0.0),
            Rgbcw {
                r: 255,
                g: 255,
                b: 255,
                c: 0,
                w: 0
            }
        );
        // Where both agree: full saturation is three colour channels, no white.
        let blended = ColourStrategy::Trapezoid(WhiteChannel::Cold)
            .apply_hs(Hs::new(120.0, 100.0).expect("in range"));
        assert_eq!(blended, raw(100.0));
    }

    /// A hue exactly on a primary takes the one-component path, and its
    /// neighbours the two-component one. Getting the boundary wrong would
    /// light two emitters for a pure red.
    #[test]
    fn a_primary_hue_lights_one_emitter() {
        let saturated =
            |hue: f64| ColourStrategy::Rgb.apply_hs(Hs::new(hue, 100.0).expect("in range"));
        assert_eq!(
            saturated(0.0),
            Rgbcw {
                r: 255,
                g: 0,
                b: 0,
                c: 0,
                w: 0
            }
        );
        assert_eq!(
            saturated(120.0),
            Rgbcw {
                r: 0,
                g: 255,
                b: 0,
                c: 0,
                w: 0
            }
        );
        assert_eq!(
            saturated(240.0),
            Rgbcw {
                r: 0,
                g: 0,
                b: 255,
                c: 0,
                w: 0
            }
        );
        // A bisector wants two at full, and gets 254 on one of them: the
        // coefficient lands a hair under 1 and the truncation takes the rest.
        // `pywizlight` does the same, so the port keeps it.
        assert_eq!(
            saturated(60.0),
            Rgbcw {
                r: 255,
                g: 254,
                b: 0,
                c: 0,
                w: 0
            }
        );
        // In between, the gamut rescale pulls one of them down for real.
        assert_eq!(
            saturated(30.0),
            Rgbcw {
                r: 255,
                g: 127,
                b: 0,
                c: 0,
                w: 0
            }
        );
    }

    #[test]
    fn a_hue_wraps_and_a_saturation_does_not() {
        assert_eq!(Hs::new(360.0, 0.0).expect("wraps").hue(), 0.0);
        assert_eq!(Hs::new(-90.0, 0.0).expect("wraps").hue(), 270.0);
        assert_eq!(Hs::new(725.0, 0.0).expect("wraps").hue(), 5.0);

        let message = Hs::new(0.0, -0.1).expect_err("negative").to_string();
        assert!(message.contains("saturation must be 0..=100"), "{message}");
        assert!(Hs::new(0.0, 100.1).is_err());
        assert!(Hs::new(f64::INFINITY, 0.0).is_err());
        assert!(Hs::new(0.0, f64::NAN).is_err());
    }

    /// The white channel the bulb reports may be either one, or larger than
    /// the blend would ever send.
    #[test]
    fn reading_back_takes_whichever_white_is_lit() {
        let cold = Rgbcw {
            r: 255,
            g: 0,
            b: 0,
            c: 64,
            w: 0,
        };
        let warm = Rgbcw {
            r: 255,
            g: 0,
            b: 0,
            c: 0,
            w: 64,
        };
        assert_eq!(cold.to_hs(), warm.to_hs());
        assert_eq!(cold.to_hs().saturation(), 75.0);

        // The WiZ app drives white past CW_MAX; it is clamped, not wrapped.
        let over = Rgbcw {
            r: 255,
            g: 0,
            b: 0,
            c: 255,
            w: 0,
        };
        let at_max = Rgbcw {
            r: 255,
            g: 0,
            b: 0,
            c: CW_MAX,
            w: 0,
        };
        assert_eq!(over.to_hs(), at_max.to_hs());
    }
}
